# Generated by Django 3.2.15 on 2022-10-03 21:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarModels', '0014_alter_trim_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=16, max_length=16, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nickname')),
                ('purchase_date', models.DateField(default=datetime.date.today, verbose_name='date purchased')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='purchase price')),
                ('is_active', models.BooleanField(default=True, help_text='e.g., if not insured', verbose_name='active')),
                ('is_archived', models.BooleanField(help_text='e.g., if in storage or sold', verbose_name='archived')),
                ('sale_date', models.DateField(default=datetime.date.today, verbose_name='date sold')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='sale price')),
                ('latest_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='latest reported mileage')),
                ('tank_capacity', models.DecimalField(decimal_places=2, help_text='in gallons [blank if alternative fuel]', max_digits=10, verbose_name='fuel tank capacity')),
                ('battery_capacity', models.DecimalField(decimal_places=2, help_text='in kWh [blank if conventional fuel/non-EV]', max_digits=10, verbose_name='battery capacity')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarModels.exteriorfinish')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarModels.model')),
                ('trim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarModels.trim')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarModels.modelyear')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
