# Generated by Django 3.2.15 on 2022-10-03 21:11

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='battery_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in kWh [blank if conventional fuel/non-EV]', max_digits=10, verbose_name='battery capacity'),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=16, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='sale_date',
            field=models.DateField(blank=True, verbose_name='date sold'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tank_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in gallons [blank if alternative fuel]', max_digits=10, verbose_name='fuel tank capacity'),
        ),
    ]
