# Generated by Django 3.2.15 on 2022-10-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20221003_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='battery_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in kWh [blank if conventional fuel/non-EV]', max_digits=10, null=True, verbose_name='battery capacity'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='sale price'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tank_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in gallons [blank if alternative fuel]', max_digits=10, null=True, verbose_name='fuel tank capacity'),
        ),
    ]
