# Generated by Django 3.2.15 on 2022-10-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20221003_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='date sold'),
        ),
    ]
