# Generated by Django 3.2.15 on 2022-10-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='exteriorfinish',
            options={'ordering': ['name'], 'verbose_name_plural': 'exterior finishes'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CarModels.brand'),
        ),
    ]
