# Generated by Django 3.2.15 on 2022-10-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarModels', '0002_auto_20221003_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelyear',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='modelyear',
            name='year',
            field=models.DecimalField(decimal_places=1, help_text="may include half-year as '.5', e.g., '1998.5'", max_digits=5, verbose_name='model year'),
        ),
    ]
