# Generated by Django 3.2.15 on 2022-10-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarModels', '0004_auto_20221003_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelyear',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
