# Generated by Django 3.2.15 on 2022-10-03 19:54

import re
from django.db import migrations
from django.utils.text import slugify

from ..models import trim_trailing_zeros

def model_year_slug(apps, schema_editor):
    ModelYear = apps.get_model("CarModels", "modelyear")

    qs = ModelYear.objects.all()

    for year in qs:
        slug_year = trim_trailing_zeros(year.year)
        slug_year = re.sub(".", "-", slug_year)
        year.slug = slugify(slug_year, allow_unicode=True)

        year.save()


class Migration(migrations.Migration):

    dependencies = [
        ('CarModels', '0005_alter_modelyear_slug'),
    ]

    operations = [
    ]
