# Generated by Django 3.2.15 on 2022-10-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarModels', '0007_auto_20221003_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='available_finishes',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='filtered_exterior_finishes',
        ),
        migrations.AddField(
            model_name='exteriorfinish',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CarModels.model', verbose_name='exterior finish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exteriorfinish',
            name='color_code',
            field=models.CharField(blank=True, help_text='e.g., #cc1111', max_length=7, verbose_name='hex color code'),
        ),
    ]
