# Generated by Django 3.2.15 on 2022-10-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarModels', '0008_auto_20221003_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trim',
            name='filtered_model_years',
            field=models.ManyToManyField(blank=True, help_text='years this trim level was not available', to='CarModels.ModelYear', verbose_name='filtered model years'),
        ),
        migrations.AlterField(
            model_name='trim',
            name='includes',
            field=models.JSONField(blank=True, help_text='see documentation for standard formatting', verbose_name='json field describing and listing options included at this trim level'),
        ),
    ]
