# Generated by Django 3.2.15 on 2022-10-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarModels', '0009_auto_20221003_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trim',
            name='includes',
            field=models.JSONField(blank=True, help_text='see documentation for standard formatting', null=True, verbose_name='json field describing and listing options included at this trim level'),
        ),
    ]
