# Generated by Django 3.2.15 on 2022-10-03 20:21

import re
from django.db import migrations
from django.utils.text import slugify

from ..models import trim_trailing_zeros

def fix_2013(apps, schema_editor):
    ModelYear = apps.get_model("CarModels", "modelyear")

    year_obj = ModelYear.objects.get(year=2013.0)
    year_slug = trim_trailing_zeros(year_obj.year)
    year_slug = re.sub("\.", "_", year_slug)
    year_obj.slug = slugify(year_slug, allow_unicode=True)


class Migration(migrations.Migration):

    dependencies = [
        ('CarModels', '0010_alter_trim_includes'),
    ]

    operations = [
        migrations.RunPython(fix_2013),
    ]
