# Generated by Django 3.2.15 on 2022-10-03 20:36

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('CarModels', '0012_auto_20221003_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trim',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=13, prefix='id_', primary_key=True, serialize=False),
        ),
    ]
