# Generated by Django 3.2.15 on 2022-10-03 20:38

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('CarModels', '0013_alter_trim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trim',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=10, prefix='', primary_key=True, serialize=False),
        ),
    ]
